### ISSUE TITLE
Trajectory planning using splines

### ISSUE THREAD

**Issue by AdamOttvar** [af-embedded/autonomous-sunfounder-picar#6]
An addition to issue #1, this will investigate and create trajectory planning using splines. In order to be able to give not only a point as desired point, but also an angle.

**Comment by AdamOttvar** [comment]
I guess this issue can be closed since all of this functionallity is available in the [PythonRobotics](https://github.com/AtsushiSakai/PythonRobotics) repo.

**Comment by ab316** [comment]
okay
